apiVersion: v1
kind: Service
metadata:
  name: {{ include "kollaber.fullname" . }}-ui
  labels:
    {{- include "kollaber.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: {{ .Values.service.ui.type }}
  ports:
    - port: {{ .Values.service.ui.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "kollaber.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ui
