// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listOrgsWithStats = `-- name: ListOrgsWithStats :many
SELECT
    o.id,
    o.name,
    o.slug,
    o.created_at,
    COUNT(DISTINCT om.user_id)::int AS member_count,
    COUNT(DISTINCT e.id)::int       AS env_count
FROM orgs o
LEFT JOIN org_members om ON om.org_id = o.id
LEFT JOIN environments e ON e.org_id = o.id
GROUP BY o.id
ORDER BY o.created_at DESC
`

type ListOrgsWithStatsRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	MemberCount int32              `json:"member_count"`
	EnvCount    int32              `json:"env_count"`
}

func (q *Queries) ListOrgsWithStats(ctx context.Context) ([]ListOrgsWithStatsRow, error) {
	rows, err := q.db.Query(ctx, listOrgsWithStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgsWithStatsRow
	for rows.Next() {
		var i ListOrgsWithStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.MemberCount,
			&i.EnvCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
