// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (event_id, user_id, body)
VALUES ($1, $2, $3)
RETURNING id, event_id, user_id, body, created_at
`

type CreateCommentParams struct {
	EventID pgtype.UUID `json:"event_id"`
	UserID  pgtype.UUID `json:"user_id"`
	Body    string      `json:"body"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.EventID, arg.UserID, arg.Body)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const listCommentsByEvent = `-- name: ListCommentsByEvent :many
SELECT id, event_id, user_id, body, created_at FROM comments
WHERE event_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListCommentsByEvent(ctx context.Context, eventID pgtype.UUID) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listCommentsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
