// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environments.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (org_id, name, cluster_name)
VALUES ($1, $2, $3)
RETURNING id, org_id, name, cluster_name, created_at
`

type CreateEnvironmentParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	Name        string      `json:"name"`
	ClusterName string      `json:"cluster_name"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment, arg.OrgID, arg.Name, arg.ClusterName)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.ClusterName,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEnvironment = `-- name: DeleteEnvironment :exec
DELETE FROM environments
WHERE id = $1 AND org_id = $2
`

type DeleteEnvironmentParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) DeleteEnvironment(ctx context.Context, arg DeleteEnvironmentParams) error {
	_, err := q.db.Exec(ctx, deleteEnvironment, arg.ID, arg.OrgID)
	return err
}

const getEnvironmentByID = `-- name: GetEnvironmentByID :one
SELECT id, org_id, name, cluster_name, created_at FROM environments WHERE id = $1
`

func (q *Queries) GetEnvironmentByID(ctx context.Context, id pgtype.UUID) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByID, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.ClusterName,
		&i.CreatedAt,
	)
	return i, err
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT id, org_id, name, cluster_name, created_at FROM environments
WHERE org_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListEnvironments(ctx context.Context, orgID pgtype.UUID) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironments, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.ClusterName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnvironment = `-- name: UpdateEnvironment :one
UPDATE environments
SET name = $3, cluster_name = $4
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, cluster_name, created_at
`

type UpdateEnvironmentParams struct {
	ID          pgtype.UUID `json:"id"`
	OrgID       pgtype.UUID `json:"org_id"`
	Name        string      `json:"name"`
	ClusterName string      `json:"cluster_name"`
}

func (q *Queries) UpdateEnvironment(ctx context.Context, arg UpdateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, updateEnvironment,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.ClusterName,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.ClusterName,
		&i.CreatedAt,
	)
	return i, err
}
