// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environments.sql

package store

import (
	"context"
)

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (name, cluster_name)
VALUES ($1, $2)
RETURNING id, name, cluster_name, created_at
`

type CreateEnvironmentParams struct {
	Name        string `json:"name"`
	ClusterName string `json:"cluster_name"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment, arg.Name, arg.ClusterName)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClusterName,
		&i.CreatedAt,
	)
	return i, err
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT id, name, cluster_name, created_at FROM environments ORDER BY created_at ASC
`

func (q *Queries) ListEnvironments(ctx context.Context) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ClusterName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
