// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (type, service, environment_id, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, type, service, environment_id, timestamp, metadata, created_at
`

type CreateEventParams struct {
	Type          string      `json:"type"`
	Service       string      `json:"service"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	Metadata      []byte      `json:"metadata"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Type,
		arg.Service,
		arg.EnvironmentID,
		arg.Metadata,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Service,
		&i.EnvironmentID,
		&i.Timestamp,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, type, service, environment_id, timestamp, metadata, created_at FROM events
ORDER BY timestamp DESC
LIMIT $1 OFFSET $2
`

type ListEventsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Service,
			&i.EnvironmentID,
			&i.Timestamp,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByEnvironment = `-- name: ListEventsByEnvironment :many
SELECT id, type, service, environment_id, timestamp, metadata, created_at FROM events
WHERE environment_id = $1
ORDER BY timestamp DESC
LIMIT $2 OFFSET $3
`

type ListEventsByEnvironmentParams struct {
	EnvironmentID pgtype.UUID `json:"environment_id"`
	Limit         int32       `json:"limit"`
	Offset        int32       `json:"offset"`
}

func (q *Queries) ListEventsByEnvironment(ctx context.Context, arg ListEventsByEnvironmentParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByEnvironment, arg.EnvironmentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Service,
			&i.EnvironmentID,
			&i.Timestamp,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
