// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listServicesByEnvironment = `-- name: ListServicesByEnvironment :many

SELECT DISTINCT e.service FROM events e
JOIN environments env ON env.id = e.environment_id
WHERE e.environment_id = $1 AND env.org_id = $2
ORDER BY e.service
`

type ListServicesByEnvironmentParams struct {
	EnvironmentID pgtype.UUID `json:"environment_id"`
	OrgID         pgtype.UUID `json:"org_id"`
}

// The queries returning a full event row are hand-written in
// internal/store/events_core.go: the table carries a stored tsvector, and sqlc
// reuses a table's struct only when a query selects every column, so generating
// them would put the search vector on the wire for every row of the timeline.
// This one returns a single text column and has no such problem.
func (q *Queries) ListServicesByEnvironment(ctx context.Context, arg ListServicesByEnvironmentParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listServicesByEnvironment, arg.EnvironmentID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var service string
		if err := rows.Scan(&service); err != nil {
			return nil, err
		}
		items = append(items, service)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
