// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvite = `-- name: AcceptInvite :exec
UPDATE invites SET accepted_at = NOW() WHERE token = $1
`

func (q *Queries) AcceptInvite(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, acceptInvite, token)
	return err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (org_id, created_by, token)
VALUES ($1, $2, $3)
RETURNING id, org_id, created_by, token, expires_at, accepted_at, created_at
`

type CreateInviteParams struct {
	OrgID     pgtype.UUID `json:"org_id"`
	CreatedBy pgtype.UUID `json:"created_by"`
	Token     string      `json:"token"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite, arg.OrgID, arg.CreatedBy, arg.Token)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CreatedBy,
		&i.Token,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteByToken = `-- name: GetInviteByToken :one
SELECT i.id, i.org_id, i.token, i.expires_at, i.accepted_at, i.created_at, o.name AS org_name
FROM invites i
JOIN orgs o ON o.id = i.org_id
WHERE i.token = $1
`

type GetInviteByTokenRow struct {
	ID         pgtype.UUID        `json:"id"`
	OrgID      pgtype.UUID        `json:"org_id"`
	Token      string             `json:"token"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	OrgName    string             `json:"org_name"`
}

func (q *Queries) GetInviteByToken(ctx context.Context, token string) (GetInviteByTokenRow, error) {
	row := q.db.QueryRow(ctx, getInviteByToken, token)
	var i GetInviteByTokenRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Token,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.OrgName,
	)
	return i, err
}
