// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID        pgtype.UUID        `json:"id"`
	EventID   pgtype.UUID        `json:"event_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Environment struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	ClusterName string             `json:"cluster_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Event struct {
	ID            pgtype.UUID        `json:"id"`
	Type          string             `json:"type"`
	Service       string             `json:"service"`
	EnvironmentID pgtype.UUID        `json:"environment_id"`
	Timestamp     pgtype.Timestamptz `json:"timestamp"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
