// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getNotificationPrefs = `-- name: GetNotificationPrefs :one
SELECT notify_on FROM notification_prefs
WHERE user_id = $1 AND org_id = $2
`

type GetNotificationPrefsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	OrgID  pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetNotificationPrefs(ctx context.Context, arg GetNotificationPrefsParams) ([]string, error) {
	row := q.db.QueryRow(ctx, getNotificationPrefs, arg.UserID, arg.OrgID)
	var notify_on []string
	err := row.Scan(&notify_on)
	return notify_on, err
}

const getOrgMembersToNotify = `-- name: GetOrgMembersToNotify :many
SELECT u.email FROM users u
JOIN org_members om ON om.user_id = u.id
LEFT JOIN notification_prefs np ON np.user_id = u.id AND np.org_id = om.org_id
WHERE om.org_id = $1 AND np.notify_on @> ARRAY[$2::text]
`

type GetOrgMembersToNotifyParams struct {
	OrgID   pgtype.UUID `json:"org_id"`
	Column2 string      `json:"column_2"`
}

func (q *Queries) GetOrgMembersToNotify(ctx context.Context, arg GetOrgMembersToNotifyParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getOrgMembersToNotify, arg.OrgID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNotificationPrefs = `-- name: UpsertNotificationPrefs :exec
INSERT INTO notification_prefs (user_id, org_id, notify_on, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (user_id, org_id) DO UPDATE
SET notify_on = EXCLUDED.notify_on, updated_at = NOW()
`

type UpsertNotificationPrefsParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	OrgID    pgtype.UUID `json:"org_id"`
	NotifyOn []string    `json:"notify_on"`
}

func (q *Queries) UpsertNotificationPrefs(ctx context.Context, arg UpsertNotificationPrefsParams) error {
	_, err := q.db.Exec(ctx, upsertNotificationPrefs, arg.UserID, arg.OrgID, arg.NotifyOn)
	return err
}
