// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orgs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrg = `-- name: CreateOrg :one
INSERT INTO orgs (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug, created_at, slack_webhook_url, teams_webhook_url, plan, stripe_customer_id, stripe_subscription_id, subscription_status, trial_ends_at
`

type CreateOrgParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, createOrg, arg.Name, arg.Slug)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.SlackWebhookUrl,
		&i.TeamsWebhookUrl,
		&i.Plan,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionStatus,
		&i.TrialEndsAt,
	)
	return i, err
}

const createOrgMember = `-- name: CreateOrgMember :exec
INSERT INTO org_members (org_id, user_id, role)
VALUES ($1, $2, $3)
`

type CreateOrgMemberParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

func (q *Queries) CreateOrgMember(ctx context.Context, arg CreateOrgMemberParams) error {
	_, err := q.db.Exec(ctx, createOrgMember, arg.OrgID, arg.UserID, arg.Role)
	return err
}

const getOrgByUserID = `-- name: GetOrgByUserID :one
SELECT o.id, o.name, o.slug, o.created_at, o.slack_webhook_url, o.teams_webhook_url, o.plan, o.stripe_customer_id, o.stripe_subscription_id, o.subscription_status, o.trial_ends_at FROM orgs o
JOIN org_members om ON om.org_id = o.id
WHERE om.user_id = $1
LIMIT 1
`

func (q *Queries) GetOrgByUserID(ctx context.Context, userID pgtype.UUID) (Org, error) {
	row := q.db.QueryRow(ctx, getOrgByUserID, userID)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.SlackWebhookUrl,
		&i.TeamsWebhookUrl,
		&i.Plan,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionStatus,
		&i.TrialEndsAt,
	)
	return i, err
}

const getOrgMember = `-- name: GetOrgMember :one
SELECT org_id, user_id, role, created_at FROM org_members WHERE org_id = $1 AND user_id = $2
`

type GetOrgMemberParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetOrgMember(ctx context.Context, arg GetOrgMemberParams) (OrgMember, error) {
	row := q.db.QueryRow(ctx, getOrgMember, arg.OrgID, arg.UserID)
	var i OrgMember
	err := row.Scan(
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listOrgsByUserID = `-- name: ListOrgsByUserID :many
SELECT o.id, o.name, o.slug, o.created_at, o.slack_webhook_url, o.teams_webhook_url, o.plan, o.stripe_customer_id, o.stripe_subscription_id, o.subscription_status, o.trial_ends_at, om.role FROM orgs o
JOIN org_members om ON om.org_id = o.id
WHERE om.user_id = $1
ORDER BY o.created_at ASC
`

type ListOrgsByUserIDRow struct {
	ID                   pgtype.UUID        `json:"id"`
	Name                 string             `json:"name"`
	Slug                 string             `json:"slug"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	SlackWebhookUrl      *string            `json:"slack_webhook_url"`
	TeamsWebhookUrl      *string            `json:"teams_webhook_url"`
	Plan                 string             `json:"plan"`
	StripeCustomerID     *string            `json:"stripe_customer_id"`
	StripeSubscriptionID *string            `json:"stripe_subscription_id"`
	SubscriptionStatus   string             `json:"subscription_status"`
	TrialEndsAt          pgtype.Timestamptz `json:"trial_ends_at"`
	Role                 string             `json:"role"`
}

func (q *Queries) ListOrgsByUserID(ctx context.Context, userID pgtype.UUID) ([]ListOrgsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listOrgsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgsByUserIDRow
	for rows.Next() {
		var i ListOrgsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.SlackWebhookUrl,
			&i.TeamsWebhookUrl,
			&i.Plan,
			&i.StripeCustomerID,
			&i.StripeSubscriptionID,
			&i.SubscriptionStatus,
			&i.TrialEndsAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrg = `-- name: UpdateOrg :one
UPDATE orgs SET name = $2, slug = $3 WHERE id = $1 RETURNING id, name, slug, created_at, slack_webhook_url, teams_webhook_url, plan, stripe_customer_id, stripe_subscription_id, subscription_status, trial_ends_at
`

type UpdateOrgParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
	Slug string      `json:"slug"`
}

func (q *Queries) UpdateOrg(ctx context.Context, arg UpdateOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, updateOrg, arg.ID, arg.Name, arg.Slug)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.SlackWebhookUrl,
		&i.TeamsWebhookUrl,
		&i.Plan,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionStatus,
		&i.TrialEndsAt,
	)
	return i, err
}
