// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: otp.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOTPCode = `-- name: CreateOTPCode :one
INSERT INTO otp_codes (email, code) VALUES ($1, $2) RETURNING id, email, code, expires_at, used_at, created_at
`

type CreateOTPCodeParams struct {
	Email string `json:"email"`
	Code  string `json:"code"`
}

func (q *Queries) CreateOTPCode(ctx context.Context, arg CreateOTPCodeParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, createOTPCode, arg.Email, arg.Code)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Code,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOTPCodesByEmail = `-- name: DeleteOTPCodesByEmail :exec
DELETE FROM otp_codes WHERE email = $1
`

func (q *Queries) DeleteOTPCodesByEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteOTPCodesByEmail, email)
	return err
}

const getValidOTPCode = `-- name: GetValidOTPCode :one
SELECT id, email, code, expires_at, used_at, created_at FROM otp_codes
WHERE email = $1 AND code = $2 AND used_at IS NULL AND expires_at > NOW()
LIMIT 1
`

type GetValidOTPCodeParams struct {
	Email string `json:"email"`
	Code  string `json:"code"`
}

func (q *Queries) GetValidOTPCode(ctx context.Context, arg GetValidOTPCodeParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, getValidOTPCode, arg.Email, arg.Code)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Code,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markOTPCodeUsed = `-- name: MarkOTPCodeUsed :exec
UPDATE otp_codes SET used_at = NOW() WHERE id = $1
`

func (q *Queries) MarkOTPCodeUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOTPCodeUsed, id)
	return err
}
