{{- if not .Values.kollaber.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-watcher.fullname" . }}-token
  labels:
    {{- include "kube-watcher.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ required "kollaber.token is required when not using existingSecret" .Values.kollaber.token | quote }}
{{- end }}
